/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imagens;

/**
 *
 * @author User
 */
public class teladecalculo extends javax.swing.JFrame {

    /**
     * Creates new form teladecalculo
     */
   
    public teladecalculo() {//construtor
        initComponents();
        painelRes.setVisible(false);
    }
//947656462 joaquim
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        btbCalc = new javax.swing.JButton();
        painelRes = new javax.swing.JLayeredPane();
        lblEc = new javax.swing.JLabel();
        lblRq = new javax.swing.JLabel();
        lblRc = new javax.swing.JLabel();
        lblVa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblRes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Informe um Numero");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Super Calculadora");

        spnValor.setModel(new javax.swing.SpinnerNumberModel(0, -50, 50, 1));

        btbCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculadora.png"))); // NOI18N
        btbCalc.setText("Calcular");
        btbCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCalcActionPerformed(evt);
            }
        });

        painelRes.setFocusTraversalPolicyProvider(true);

        lblEc.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 10)); // NOI18N
        lblEc.setForeground(new java.awt.Color(0, 0, 255));
        lblEc.setText("0");

        lblRq.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 10)); // NOI18N
        lblRq.setForeground(new java.awt.Color(0, 0, 255));
        lblRq.setText("0");

        lblRc.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 10)); // NOI18N
        lblRc.setForeground(new java.awt.Color(0, 0, 255));
        lblRc.setText("0");

        lblVa.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 10)); // NOI18N
        lblVa.setForeground(new java.awt.Color(0, 0, 255));
        lblVa.setText("0");

        jLabel3.setText("Resto da divisão por 2");

        jLabel4.setText("Elevado ao Cubo");

        jLabel5.setText("Raiz Quadrada");

        jLabel6.setText("Raiz Cúbica");

        jLabel7.setText("Valor absoluto");

        lblRes.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 10)); // NOI18N
        lblRes.setForeground(new java.awt.Color(0, 0, 255));
        lblRes.setText("0");

        painelRes.setLayer(lblEc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelRes.setLayer(lblRq, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelRes.setLayer(lblRc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelRes.setLayer(lblVa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelRes.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelRes.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelRes.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelRes.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelRes.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelRes.setLayer(lblRes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelResLayout = new javax.swing.GroupLayout(painelRes);
        painelRes.setLayout(painelResLayout);
        painelResLayout.setHorizontalGroup(
            painelResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(painelResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(35, 35, 35)
                .addGroup(painelResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEc)
                    .addComponent(lblRes)
                    .addComponent(lblRq)
                    .addComponent(lblRc)
                    .addComponent(lblVa))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        painelResLayout.setVerticalGroup(
            painelResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResLayout.createSequentialGroup()
                .addGroup(painelResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelResLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(painelResLayout.createSequentialGroup()
                        .addComponent(lblRes)
                        .addGap(18, 18, 18)
                        .addComponent(lblEc)
                        .addGap(18, 18, 18)
                        .addComponent(lblRq)
                        .addGap(18, 18, 18)
                        .addComponent(lblRc)
                        .addGap(18, 18, 18)
                        .addComponent(lblVa)))
                .addGap(0, 65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btbCalc)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addComponent(btbCalc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelRes)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCalcActionPerformed
        // TODO add your handling code here:
        painelRes.setVisible(true);
        int x = Integer.parseInt(spnValor.getValue().toString());
        
        //RAIZ QUADRADA
        double rq = Math.sqrt(x);
        //lblRq.setText(Double.toString(Math.sqrt(rq))); (Essa maneira retorna o valor inteiro)
        lblRq.setText(String.format("%.2f",rq));//Essa instrucao reduz a 2 casas decimais
        
        //RAIZ CUBICA
        double rc = Math.cbrt(x);
        //lblRc.setText(Double.toString(Math.cbrt(rc)));
        lblRc.setText(String.format("%.2f",rc));        
        
        //ELEVADO AO CUBO
        lblEc.setText(Integer.toString((int)Math.pow(x, 3)));
        
        //RESTO DA DIVISAO POR 2
        lblRes.setText(Integer.toString((int)x%2));
        
        //NUMERO ABSOLUTO
        lblVa.setText(Integer.toString((int)Math.abs(x)));
        
        
        
    }//GEN-LAST:event_btbCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teladecalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teladecalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teladecalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teladecalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teladecalculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCalc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblEc;
    private javax.swing.JLabel lblRc;
    private javax.swing.JLabel lblRes;
    private javax.swing.JLabel lblRq;
    private javax.swing.JLabel lblVa;
    private javax.swing.JLayeredPane painelRes;
    private javax.swing.JSpinner spnValor;
    // End of variables declaration//GEN-END:variables
}
